name: Release (Production)

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - uses: dominikh/staticcheck-action@024238d2898c874f26d723e7d0ff4308c35589a2 #v1.4.0
        with:
          version: "2025.1.1"
          install-go: "false"

  test:
    name: Test
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Run tests
        run: |
          go test ./... -coverprofile coverage.out

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    permissions:
      contents: write
      packages: write
    env:
      CGO_ENABLED: 0
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Determine goreleaser args
        id: goreleaser-args
        run: |
          if git describe --exact-match --tags HEAD >/dev/null 2>&1; then
            echo "args=--verbose" >> "$GITHUB_OUTPUT"
            echo "is_release=true" >> "$GITHUB_OUTPUT"
          else
            echo "args=--snapshot --skip=publish,docker --verbose" >> "$GITHUB_OUTPUT"
            echo "is_release=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Login to GHCR
        if: steps.goreleaser-args.outputs.is_release == 'true'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 #v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a #v6.4.0
        with:
          version: "~> v2"
          args: ${{ steps.goreleaser-args.outputs.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable experimental docker features
        if: steps.goreleaser-args.outputs.is_release == 'true'
        run: |
          mkdir -p ~/.docker/ && \
          echo '{"experimental": "enabled"}' > ~/.docker/config.json
      - name: Create manifest for version
        if: steps.goreleaser-args.outputs.is_release == 'true'
        run: |
          export DH_TAG=$(git tag --points-at HEAD | sed 's/^v*//')
          docker manifest create \
            ghcr.io/apivzero/watchtower:$DH_TAG \
            ghcr.io/apivzero/watchtower:amd64-$DH_TAG \
            ghcr.io/apivzero/watchtower:i386-$DH_TAG \
            ghcr.io/apivzero/watchtower:armhf-$DH_TAG \
            ghcr.io/apivzero/watchtower:arm64v8-$DH_TAG
      - name: Annotate manifest for version
        if: steps.goreleaser-args.outputs.is_release == 'true'
        run: |
          docker manifest annotate \
            ghcr.io/apivzero/watchtower:$(echo $TAG | sed 's/^v*//') \
            ghcr.io/apivzero/watchtower:i386-$(echo $TAG | sed 's/^v*//') \
            --os linux \
            --arch 386

          docker manifest annotate \
            ghcr.io/apivzero/watchtower:$(echo $TAG | sed 's/^v*//') \
            ghcr.io/apivzero/watchtower:armhf-$(echo $TAG | sed 's/^v*//') \
            --os linux \
            --arch arm

          docker manifest annotate \
            ghcr.io/apivzero/watchtower:$(echo $TAG | sed 's/^v*//') \
            ghcr.io/apivzero/watchtower:arm64v8-$(echo $TAG | sed 's/^v*//') \
            --os linux \
            --arch arm64 \
            --variant v8
      - name: Create manifest for latest
        if: steps.goreleaser-args.outputs.is_release == 'true'
        run: |
          docker manifest create \
            ghcr.io/apivzero/watchtower:latest \
            ghcr.io/apivzero/watchtower:amd64-latest \
            ghcr.io/apivzero/watchtower:i386-latest \
            ghcr.io/apivzero/watchtower:armhf-latest \
            ghcr.io/apivzero/watchtower:arm64v8-latest
      - name: Annotate manifest for latest
        if: steps.goreleaser-args.outputs.is_release == 'true'
        run: |
          docker manifest annotate \
            ghcr.io/apivzero/watchtower:latest \
            ghcr.io/apivzero/watchtower:i386-latest \
            --os linux \
            --arch 386

          docker manifest annotate \
            ghcr.io/apivzero/watchtower:latest \
            ghcr.io/apivzero/watchtower:armhf-latest \
            --os linux \
            --arch arm

          docker manifest annotate \
            ghcr.io/apivzero/watchtower:latest \
            ghcr.io/apivzero/watchtower:arm64v8-latest \
            --os linux \
            --arch arm64 \
            --variant v8
      - name: Push manifests to GHCR
        if: steps.goreleaser-args.outputs.is_release == 'true'
        run: |
          docker manifest push ghcr.io/apivzero/watchtower:$(echo $TAG | sed 's/^v*//') && \
            docker manifest push ghcr.io/apivzero/watchtower:latest

  renew-docs:
    name: Refresh pkg.go.dev
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Pull new module version
      uses: andrewslotin/go-proxy-pull-action@50fea06a976087614babb9508e5c528b464f4645 #master@2022-10-14
